# See https://www.getzola.org/documentation/getting-started/configuration/
base_url = "https://whatsdown.dog"

# TODO
title = "Downdog | Software reliability experts"
description = "Downdog is an SRE consultancy specializing in reliability, observability, performance, and CI/CD. Founded by engineers from Discord, Shopify, and Lightstep."
author = "hello@whatsdown.dog (Downdog, Inc.)"

# TODO
# theme = ""

output_dir = "build"
ignored_static = []
ignored_content = []

compile_sass = true
minify_html = true

generate_feeds = false

build_search_index = true
generate_sitemap = true
generate_robots_txt = true

# TODO
taxonomies = []

[markdown]
render_emoji = true
# ???
external_links_no_referrer = true
bottom_footnotes = true

[markdown.highlighting]
theme = "gruvbox-dark-hard"

# TODO
[slugify]

# TODO
[search]

[extra]
# Put all your custom variables here
