name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build only
        # TODO: We might want to make our own action to ensure Zola is up-to-date
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          BUILD_FLAG: "--drafts"
